import puppeteer from "puppeteer";

let browserInstance = null;
let browserLaunchPromise = null;

const getBrowser = async () => {
  if (browserInstance && browserInstance.connected) {
    return browserInstance;
  }

  if (browserLaunchPromise) {
    return browserLaunchPromise;
  }

  console.log('🚀 Launching browser...');

  browserLaunchPromise = puppeteer.launch({
    headless: 'new',
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--no-first-run',
      '--no-zygote',
      '--single-process', // CRITICAL for Render
      '--disable-extensions',
      '--disable-web-security',
      '--disable-features=IsolateOrigins,site-per-process'
    ],
    // Add these for Render compatibility
    executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
    timeout: 60000
  });

  try {
    browserInstance = await browserLaunchPromise;
    console.log('✅ Browser launched successfully');
    
    browserInstance.on('disconnected', () => {
      console.log("⚠️ Browser disconnected");
      browserInstance = null;
      browserLaunchPromise = null;
    });

    return browserInstance;
  } catch (error) {
    console.error('❌ Browser launch failed:', error.message);
    browserLaunchPromise = null;
    throw error;
  } finally {
    browserLaunchPromise = null;
  }
};

export const generatePDF = async (req, res) => {
  console.log("🔥 PDF GENERATION STARTED 🔥");

  let page;
  let pageCreated = false;

  try {
    const { htmlContent, filename = "BRisk_Report.pdf" } = req.body;

    if (!htmlContent) {
      return res.status(400).json({ error: "HTML content is required" });
    }

    console.log("📊 HTML Content size:", htmlContent.length, "characters");

    const browser = await getBrowser();
    
    page = await browser.newPage();
    pageCreated = true;
    
    console.log("📄 Page created");

    // Set timeouts
    await page.setDefaultTimeout(60000);
    await page.setDefaultNavigationTimeout(60000);

    await page.setViewport({
      width: 1200,
      height: 1600,
      deviceScaleFactor: 1
    });

    console.log("🔄 Setting content...");

    // Set content with timeout
    await page.setContent(htmlContent, {
      waitUntil: "networkidle0",
      timeout: 60000
    });

    console.log("✅ Content loaded");

    // Wait for charts/images to render
    await page.evaluate(() => {
      return new Promise(resolve => setTimeout(resolve, 2000));
    });

    console.log("📸 Generating PDF...");

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,

      headerTemplate: `
        <div style="
          width:100%;
          font-size:10px;
          padding:6px 40px;
          box-sizing:border-box;
          color:#333;
          border-bottom:1px solid #e5e7eb;
          font-family:Arial, sans-serif;
        ">
          <span style="font-weight:600">
            <span style="color:#1d1ac9ff">STARTUP</span><span style="color: #FFFF00">VISORS</span>
          </span>
        </div>
      `,

      footerTemplate: `
        <div style="
          width:100%;
          font-size:9px;
          padding:6px 40px;
          box-sizing:border-box;
          color:#666;
          border-top:1px solid #e5e7eb;
          font-family:Arial, sans-serif;
          display:flex;
          justify-content:space-between;
        ">
          <span>Generated by Startupvisors</span>
          <span>
            Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </span>
        </div>
      `,

      margin: {
        top: "30mm",
        bottom: "22mm",
        left: "8mm",
        right: "8mm"
      },

      timeout: 60000
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${filename}"`
    );

    res.end(pdfBuffer);
    console.log("✅ PDF GENERATED SUCCESSFULLY");

  } catch (error) {
    console.error("❌ PDF Error:", error.message);
    console.error("❌ Stack:", error.stack);
    
    if (!res.headersSent) {
      res.status(500).json({ 
        error: "Failed to generate PDF",
        details: error.message 
      });
    }

  } finally {
    if (pageCreated && page) {
      try {
        await page.close();
        console.log("🔒 Page closed");
      } catch (err) {
        console.error("Error closing page:", err.message);
      }
    }
  }
};

// Graceful shutdown
process.on('SIGINT', async () => {
  console.log("🛑 Shutting down...");
  if (browserInstance) {
    await browserInstance.close();
  }
  process.exit(0);
});

process.on('SIGTERM', async () => {
  console.log("🛑 Shutting down...");
  if (browserInstance) {
    await browserInstance.close();
  }
  process.exit(0);
});